[package]
name = "hands_on"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ "hello_bevy","hello_world", "my_library", "pig"]

[workspace.dependencies]
bevy = { version = "0.16.1" }
bevy_egui = "0.34"
