[package]
name = "physics"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_rapier2d = "0.31.0"

# Add this to your Cargo.toml
[profile.dev.package.bevy_rapier3d]
opt-level = 3

# Add this to your Cargo.toml
[profile.release]
codegen-units = 1
